apiVersion: v2
name: olake
description: A Helm chart for OLake UI - Fastest open-source tool for replicating Databases to Apache Iceberg or Data Lakehouse
type: application
version: 0.0.7
appVersion: "0.2.3"
home: https://github.com/datazip-inc/olake-helm
sources:
  - https://github.com/datazip-inc/olake-helm
keywords:
  - data-pipeline
  - elt
  - kubernetes
  - apache
  - iceberg
  - data-lakehouse
  - workflow
  - olake
maintainers:
  - name: Team OLake
    email: hello@olake.io
dependencies: []
annotations:
  helm.sh/schema-validation: "true" # Enable schema validation for this chart
