{{- /*
TODO: Remove the Helm hook logic in a future release (e.g. v1.0.0).
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: olake-workers-secret
  namespace: {{ include "olake.namespace" . }}
  annotations:
    {{- if not .Values.useStandardResources }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "53"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc }}