apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olake.workerServiceAccountName" . }}
  namespace: {{ include "olake.namespace" . }}
  annotations:
    {{- if not .Values.useStandardResources }}
    "helm.sh/hook": pre-install # pre-upgrade was removed to avoid race conditions during upgrade process
    "helm.sh/hook-weight": "50"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with .Values.olakeWorker.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers