{{- if not .Values.nfsServer.enabled }}
{{- if not .Values.nfsServer.external.storageClass }}
{{- fail "nfsServer.external.storageClass is required when nfsServer.enabled is false" }}
{{- end }}
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "olake.sharedStoragePVC" . }}
  namespace: {{ include "olake.namespace" . }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared-storage
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{- if .Values.nfsServer.enabled }} {{ include "olake.sharedStorageSize" . }}{{- else }} {{ .Values.nfsServer.external.size }}{{- end }}
  storageClassName: {{- if .Values.nfsServer.enabled }} {{ .Values.nfsServer.storageClass.name | default "nfs-server" }}{{- else }} {{ .Values.nfsServer.external.storageClass }}{{- end }}
